#!/bin/bash
# Copyright (C) 2015-2016 DragonTC
# Copyright (C) 2015-2016 UBERROMS - UBERLLVM
#
# Licensed under the Apache License, Version 2.0 (the "License");
#   You may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

# Define Color Values
red=$(tput setaf 1) # red
grn=$(tput setaf 2) # green
blu=$(tput setaf 4) # blue
cya=$(tput setaf 6) # cyan
txtbld=$(tput bold) # Bold
bldred=${txtbld}$(tput setaf 1) # red
bldgrn=${txtbld}$(tput setaf 2) # green
bldblu=${txtbld}$(tput setaf 4) # blue
bldcya=${txtbld}$(tput setaf 6) # cyan
txtrst=$(tput sgr0) # Reset

CPUS=$(grep "^processor" /proc/cpuinfo | wc -l)
DATE=date

# Optimize CPU Threads
JOBS=$(bc <<< "$CPUS+2");

# Set Prefix Path
PREFIX_PATH=$TOOLCHAIN_ROOT/out/$UBERCLANG_VERSION

alias popd="popd > /dev/null"
alias pushd="pushd > /dev/null"

# Function to clean tree
clean() {
  if [ -d $TOOLCHAIN_ROOT/cmake ];
  then
    rm -rf $TOOLCHAIN_ROOT/cmake;
  fi;

  if [ -d "$PREFIX_PATH" ];
  then
    rm -rf $TOOLCHAIN_ROOT/out;
    mkdir -p $PREFIX_PATH;
    echo "Emptied the out directory";
  else
    mkdir -p $PREFIX_PATH;
  fi;

  cd $TOOLCHAIN_ROOT;
  pushd llvm && git fetch ll $UBERCLANG_VERSION && git reset --hard FETCH_HEAD && popd ;
  pushd llvm/tools/clang && rm -rf * && git fetch ll $UBERCLANG_VERSION && git reset --hard FETCH_HEAD && popd;
  pushd llvm/tools/polly && rm -rf * && git fetch ll $UBERCLANG_VERSION && git reset --hard FETCH_HEAD && popd;
  pushd llvm/projects/compiler-rt && rm -rf * && git fetch ll $UBERCLANG_VERSION && git reset --hard FETCH_HEAD && popd;
  pushd llvm/projects/libcxx && rm -rf * && git fetch ll $UBERCLANG_VERSION && git reset --hard FETCH_HEAD && popd;
  pushd llvm/projects/libcxxabi && rm -rf * && git fetch ll $UBERCLANG_VERSION && git reset --hard FETCH_HEAD && popd;
  pushd llvm/projects/libunwind && rm -rf * && git fetch ll $UBERCLANG_VERSION && git reset --hard FETCH_HEAD && popd;
  pushd llvm/projects/openmp && rm -rf * && git fetch ll $UBERCLANG_VERSION && git reset --hard FETCH_HEAD && popd;
}

# Function to build LLVM
build() {

export CC="gcc";
export CXX="g++";

# Speed up build with gold
export LD="ld.gold"

# Concatenate all flags
COMMON_CXX_FLAGS="-O3 -Wno-macro-redefined -pipe -pthread -fopenmp -g0 $LOCAL_CXX_FLAGS"
COMMON_C_FLAGS="-O3 -Wno-macro-redefined -pipe -pthread -fopenmp -g0 $LOCAL_C_FLAGS"

# Configure LLVM with CMAKE
mkdir $TOOLCHAIN_ROOT/cmake;
cd $TOOLCHAIN_ROOT/cmake;

cmake -DLINK_POLLY_INTO_TOOLS:BOOL=ON -DCMAKE_CXX_FLAGS:STRING="$COMMON_CXX_FLAGS" -DCMAKE_C_FLAGS:STRING="$COMMON_C_FLAGS" -DLLVM_ENABLE_PIC:BOOL=ON -DCMAKE_INSTALL_PREFIX:PATH=$PREFIX_PATH -DLLVM_PARALLEL_COMPILE_JOBS=$JOBS -DLLVM_PARALLEL_LINK_JOBS=$JOBS -DLLVM_ENABLE_THREADS:BOOL=ON -DLLVM_ENABLE_WARNINGS:BOOL=OFF -DLLVM_ENABLE_WERROR:BOOL=OFF -DLLVM_BUILD_DOCS:BOOL=OFF -DLLVM_BUILD_DOXYGEN:BOOL=OFF -DLLVM_INCLUDE_EXAMPLES:BOOL=OFF -DLLVM_INCLUDE_TESTS:BOOL=OFF -DLLVM_BINUTILS_INCDIR:PATH=$TOOLCHAIN_ROOT/llvm/tools/binutils/include -DLLVM_TARGETS_TO_BUILD:STRING="X86;ARM;AArch64" -DCMAKE_BUILD_TYPE:STRING=MinSizeRel -DLLVM_OPTIMIZED_TABLEGEN:BOOL=ON -DPOLLY_ENABLE_GPGPU_CODEGEN:BOOL=ON $TOOLCHAIN_ROOT/llvm;

# Find Time Before Build
START_TIME=$($DATE +%s);

# Build LLVM
if ! time cmake --build . -- -j$JOBS; then
  echo "";
  echo -e ${red} "*************************************" ${txtrst};
  echo -e ${red} "    Clang has failed to compile!" ${txtrst};
  echo -e ${red} "*************************************" ${txtrst};
  exit 1;
else
  cmake --build . --target install -- -j$JOBS;
  # Echo Time if Build Finishes
  END_TIME=$($DATE +%s);
  tmin=$(( (END_TIME-START_TIME)/60 ));
  tsec=$(( (END_TIME-START_TIME)%60 ));
  echo -e "";
  echo -e ${grn} "**************************************" ${txtrst};
  echo -e ${grn} "  Clang has compiled successfully!" ${txtrst};
  echo -e ${grn} "**************************************" ${txtrst};
  echo -e  "";
  echo -e ${bldgrn}"Total time elapsed:${txtrst} ${grn}$tmin minutes $tsec seconds"${txtrst};
  echo -e ${bldgrn}"Toolchain located at:${txtrst} ${grn}$PREFIX_PATH"${txtrst};
fi;

# Unset Local Variables
unset TOOLCHAIN_ROOT;
unset UBERCLANG_VERSION;
unset PREFIX_PATH;
unset LOCAL_CXX_FLAGS;
unset LOCAL_C_FLAGS;
unset CC;
unset CXX;
unset LD;
}

clean;
build;
